# Generated by Django 4.0 on 2021-12-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congratulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_who', models.CharField(max_length=50, verbose_name='Для кого')),
                ('text_on_card', models.TextField(verbose_name='Текст на главной странице')),
                ('slug', models.SlugField(unique=True, verbose_name='Семантический идентификатор')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Поздравление',
                'verbose_name_plural': 'Поздравления',
            },
        ),
    ]
